name: Gravestone
version: '${project.version}'
main: be.thatsatim.gravestone.Gravestone
api-version: '1.20'
author: ThatsATim

dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
      join-classpath: true